export * from './user-actions';
export * from './product-actions';
export * from './cart-actions';

export const Action = {

  ERROR: "ERROR",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  SIGNUP: "SIGNUP",
  LOGIN_WITH_FACEBOOK: "LOGIN_WITH_FACEBOOK",
  LOGIN_WITH_GOOGLE: "LOGIN_WITH_GOOGLE",
  ///
  CURRENT_PRODUCT: "CURRENT_PRODUCT",
  ALL_PRODUCTS: "ALL_PRODUCTS",
  LIST_PRODUCT_IMAGE: "LIST_PRODUCT_IMAGE",

  ///
  GET_CART: "GET_CART",
  ADD_TO_CART: "ADD_TO_CART",
  UPDATE_FROM_CART: "UPDATE_FROM_CART",
  DELETE_TO_CART_ITEM: "DELETE_TO_CART_ITEM",
  CLEAR_CART_ITEMS: "CLEAR_CART_ITEMS",
  //
  CALL_DATA: "CALL_DATA",



  // PROFILE: "PROFILE",
  // DISSMISS: "DISSMISS",

  // LANDING_PRODUCTS: "LANDING_PRODUCTS",
  // PRODUCT_DETAILS: "PRODUCT_DETAILS",
  // ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  // REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",


  // ADDED_NEW_ADDRESS: "ADDED_NEW_ADDRESS",

  // PLACE_ORDER: "PLACE_ORDER"


};