export const payments = [
    {
        id: 0,
        userid: 2,
        type: 'visa',
        cardHolder: 'Nguyen Van Ti',
        cardNumber: '2156995348483902',
        expirationMonth: '09',
        expirationYear: '24',
        cvv: '129',
        isDefault: 1,
    },
    {
        id: 1,
        userid: 2,
        type: 'mastercard',
        cardHolder: 'Nguyen Van Cuong',
        cardNumber: '6969305376959634',
        expirationMonth: '04',
        expirationYear: '27',
        cvv: '323',
        isDefault: 0,
    },
    {
        id: 2,
        userid: 2,
        type: 'mastercard',
        cardHolder: 'Nguyen Anh Tai',
        cardNumber: '4848053396452940',
        expirationMonth: '04',
        expirationYear: '30',
        cvv: '563',
        isDefault: 0,
    },
];
