import { faker } from "@faker-js/faker";

const pages_management = [
  {
    id: faker.string.uuid(),
    label: "Women",
    path: "Women",
    description: "test",
    dateAdded: faker.date.past(),
    dateModified: faker.date.recent(),
    status: "publish",
  },
  {
    id: faker.string.uuid(),
    label: "Men",
    path: "Women",
    description: "tes545fghgft",
    dateAdded: faker.date.past(),
    dateModified: faker.date.recent(),
    status: "publish",
  },
  {
    id: faker.string.uuid(),
    label: "Clothing",
    description: "tawerest",
    path: "Women",
    dateAdded: faker.date.past(),
    dateModified: faker.date.recent(),
    status: "publish",
  },
  {
    id: faker.string.uuid(),
    label: "Accessories",
    description: "tesvrvt",
    path: "Men",
    dateAdded: faker.date.past(),
    dateModified: faker.date.recent(),
    status: "trash",
  },
  {
    id: faker.string.uuid(),
    label: "Brands",
    description: "tebxvdest",
    path: "Women",
    dateAdded: faker.date.past(),
    dateModified: faker.date.recent(),
    status: "draft",
  },
  {
    id: faker.string.uuid(),
    label: "Tops",
    description: "test23f",
    path: "Men",
    dateAdded: faker.date.past(),
    dateModified: faker.date.recent(),
    status: "draft",
  },
  {
    id: faker.string.uuid(),
    label: "Dresses",
    description: "tesnnnnt",
    path: "Women",
    dateAdded: faker.date.past(),
    dateModified: faker.date.recent(),
    status: "draft",
  },
  {
    id: faker.string.uuid(),
    label: "Bags",
    description: "teswwwt",
    path: "Men",
    dateAdded: faker.date.past(),
    dateModified: faker.date.recent(),
    status: "trash",
  },
  {
    id: faker.string.uuid(),
    label: "Hats",
    description: "tessdfgt",
    path: "Men",
    dateAdded: faker.date.past(),
    dateModified: faker.date.recent(),
    status: "publish",
  },
  {
    id: faker.string.uuid(),
    label: "Fjallraven",
    description: "tesgfsdgt",
    path: "Women",
    dateAdded: faker.date.past(),
    dateModified: faker.date.recent(),
    status: "publish",
  },
  {
    id: faker.string.uuid(),
    label: "North face",
    description: "tegsgfst",
    path: "Women",
    dateAdded: faker.date.past(),
    dateModified: faker.date.recent(),
    status: "publish",
  },
  {
    id: faker.string.uuid(),

    label: "Gucci",
    description: "tesbsdfbsd",
    path: "Bags",
    dateAdded: faker.date.past(),
    dateModified: faker.date.recent(),
    status: "draft",
  },
  {
    id: faker.string.uuid(),
    label: "Louis Vuitton",
    description: "test31231",
    path: "Tops",
    dateAdded: faker.date.past(),
    dateModified: faker.date.recent(),
    status: "trash",
  },
  {
    id: faker.string.uuid(),
    label: "Supreme",
    description: "test12321",
    path: "Accessories",
    dateAdded: faker.date.past(),
    dateModified: faker.date.recent(),
    status: "draft",
  },
];

export default pages_management;
